version: '3.9'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./src:/opt/bitnami/spark/jobs
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 4g
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
    HADOOP_USER_NAME: hadoop
    HOME: /opt/bitnami/spark
  networks:
    - datamasterylab

services:
  spark-master:
    image: bitnami/spark:latest
    volumes:
      - ./src:/opt/bitnami/spark/jobs
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      HADOOP_USER_NAME: hadoop
      HOME: /opt/bitnami/spark
    networks:
      - datamasterylab

  spark-worker-1:
    <<: *spark-common
    hostname: spark-worker-1

  spark-worker-2:
    <<: *spark-common
    hostname: spark-worker-2

networks:
  datamasterylab:
    driver: bridge